apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth # select all pods with the auth label
  template:
    metadata:
      labels:
        app: auth # give all the pods an auth label
    spec:
      containers:
        - name: auth # only used for logging purposes
          image: cstudent/auth
          env:
            - name: PGHOST
              value: "auth-postgres-cluster-ip"
            - name: PGUSER
              value: "auth"
            - name: PGDATABASE
              value: "auth-database"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: JWT_KEY
