apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: cstudent/payments
          env:
            - name: PGHOST
              value: "payments-postgres-cluster-ip"
            - name: PGUSER
              value: "payments"
            - name: PGDATABASE
              value: "payments-database"
            - name: PGPASSWORD
              value: "${POSTGRES_PASSWORD}"
            - name: JWT_KEY
              value: "${JWT_KEY}"
            - name: STRIPE_KEY
              value: "${STRIPE_KEY}"
