apiVersion: v1
kind: Service
metadata:
  name: payments-postgres-svc
spec:
  selector:
    app: payments-postgres
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
