apiVersion: v1
kind: Service
metadata:
  name: products-postgres-cluster-ip
spec:
  selector:
    app: products-postgres
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
