apiVersion: v1
kind: Service
metadata:
  name: products-cluster-ip
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3000       # the port other pods use to talk to this service
      targetPort: 3000 # the port that this service uses to talk to its pods
