apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
        - name: orders-postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "orders-database"
            - name: POSTGRES_USER
              value: "orders"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
