apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: cstudent/orders
          env:
            - name: PGHOST
              value: "orders-postgres-cluster-ip"
            - name: PGUSER
              value: "orders"
            - name: PGDATABASE
              value: "orders-database"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: weibuddies-secrets
                  key: JWT_KEY
            - name: KAFKA_ADVERTISED_LISTENERS
              value: kafka-0.kafka-svc.kafka-kraft.svc.cluster.local:9092
