apiVersion: v1
kind: Service
metadata:
  name: orders-postgres-cluster-ip
spec:
  selector:
    app: orders-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
